### ISSUE TITLE
gdp

### ISSUE THREAD

**Issue by maksakovsky** [thecapitalistcycle/reproduction-schemes#4]
https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)
this is closer to a population chart than gdp chart makes little sense to me. If they watch 50 year old 10 inch tv's in botswana that is not the same as 60 inch tv's in aaustralia, it obviously isnt apples for apples

**Comment by maksakovsky** [comment]
https://www.investopedia.com/terms/r/realgdp.asp

while this may have dollar based prices the dollar is the international currency and easily converted. Barter is not generally considered in gdp so again botswana may be at a disadvantage. This would definitely seem a better gauge for ranking countries. 
other issues are population increases etc

**Comment by maksakovsky** [comment]
https://www.economist.com/briefing/2016/04/30/the-trouble-with-gdp
seems people want to increase GDP by adding thing such as housework which has always been there but if anything, with better tools and more eating in cafes, there is less housework. seems some confusion as to what gdp measures and what people want to use it for. 

Had never thought gdp was or should be a measurement of everything everyone did including brushing your teeth and cutting your nails but rather a measurement of the output of society that was exchanged for money. Not sure if I would include inventories until they were sold. 


https://www.weforum.org/agenda/2016/04/five-measures-of-growth-that-are-better-than-gdp/

again trying to use gdp as measure of happiness etc. While the measurements suggested are interesting and are definitely things one would like to measure think it was a mistake in the first place to think that gdp could/would measure these things.

**Comment by maksakovsky** [comment]
https://www.thebalance.com/gdp-by-country-3-ways-to-compare-3306012
china ranks 104 per capita using ppp on this site but is doubled in gdp using that method. using the mcdonalds index then china would climb to the top of the ladder and assume australia would plummett as macca's are expensive here. the ppp assumes that a teacher engineer in china has the same value as one in usa etc real problems here again apples just aint apples

**Comment by dentarthur** [comment]
here is the list you should focus on:

https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita

Looks plausible to me. Few small rich countries at top.

Main ones in reasonable relative positions to Botswana eg IMF ranking column:

USA 11

Australia 18

Russia 48

Botswana 71

China 79

Relative numbers more meaningful than ranks.

**Comment by dentarthur** [comment]
Details of PPP calculations:

http://unstats.un.org/unsd/publication/SeriesF/SeriesF_62E.pdf

**Comment by maksakovsky** [comment]
what is the difference between this and the real gdp per head rankins which have china 84-90?

Sent: Thursday, January 10, 2019 at 11:05 PM

**Comment by dentarthur** [comment]
Dont know. Difference in rankings 70 or 80 to 90 does not seem interesting.

Comparing ratios of actual per capita for two countries (ignoring rankings)
should give more stable trend with PPP. Less affected by xchange rate
fluctuations.

**Comment by maksakovsky** [comment]
https://www.thebalance.com/gdp-by-country-3-ways-to-compare-3306012
china ranks 104 per capita using ppp on this site but is doubled in gdp using that method. using the mcdonalds index then china would climb to the top of the ladder and assume australia would plummett as macca's are expensive here. the ppp assumes that a teacher engineer in china has the same value as one in usa etc real problems here again apples just aint apples

**Comment by maksakovsky** [comment]
if a banana in botswana is 5c equivalent of local currency so it is cheap for me but just ok for botswanians however when they come here it is 50c for a banana which is ok for me but out of the question for them then it matters re currency. Everything in US$'s tells you what it costs wherever you are and with globalisation that is the point. the local equivalent becomes less relevant every day.

**Comment by maksakovsky** [comment]
just got this as it was in spam
 

Sent: Friday, January 11, 2019 at 10:22 PM
